export interface TrustPatternGuidance {
  title: string
  description: string
  designConsiderations: string[]
  relatedPatterns: string[]
  examples: string[]
}

export type TrustPatternKey =
  | 'caveat'
  | 'consent-manager'
  | 'data-ownership'
  | 'disclosure'
  | 'footprints'
  | 'incognito-mode'
  | 'watermark'
  | 'citation-marks'

export const trustPatternGuidance: Record<
  TrustPatternKey,
  TrustPatternGuidance
> = {
  caveat: {
    title: 'Caveat',
    description:
      'Inform users about shortcomings or risks in the model or technology overall, giving vital context before they proceed.',
    designConsiderations: [
      'Summarize the limitation in plain language and avoid legal jargon.',
      'Clarify whether the risk is systemic (always present) or situational (based on the current task).',
      'Link to mitigation guidance or next steps where appropriate.',
    ],
    relatedPatterns: ['Consent Manager', 'Controls', 'Footprints'],
    examples: [
      'Warn that generated medical advice must be reviewed by a licensed professional.',
      'Highlight when training data cuts off before a specific year.',
    ],
  },
  'consent-manager': {
    title: 'Consent',
    description:
      'Capture data from others only with their knowledge and permission, respecting policies and privacy requirements.',
    designConsiderations: [
      'Call out required vs. optional consents so users know what is mandatory.',
      'Record who granted consent and when for audit trails.',
      'Allow consent to be revoked and communicate the impact of revocation.',
    ],
    relatedPatterns: ['Data Ownership', 'Memory', 'Controls'],
    examples: [
      'Request permission before analyzing customer transcripts.',
      'Ask collaborators to opt in before the assistant shares their notes.',
    ],
  },
  'data-ownership': {
    title: 'Data ownership',
    description:
      'Let people control what information the model remembers, how it is stored, and whether it is reused.',
    designConsiderations: [
      'Provide clear retention settings (session-only, project, always).',
      'Show a summary of stored data and allow one-click deletion.',
      'Explain the benefits or trade-offs of remembering versus forgetting.',
    ],
    relatedPatterns: ['Consent Manager', 'Memory', 'Incognito Mode'],
    examples: [
      'Opt out of saving prompts that contain personal identifiers.',
      'Download a copy of stored interactions for compliance review.',
    ],
  },
  disclosure: {
    title: 'Disclosure',
    description:
      'Clearly mark content and interactions guided or delivered by AI, ensuring users know when they are interacting with automation.',
    designConsiderations: [
      'Use consistent placement and styling so disclosures are never missed.',
      'Differentiate between human-authored and AI-authored sections.',
      'Make the disclosure detectable by assistive technologies.',
    ],
    relatedPatterns: ['Watermark', 'Citations', 'Stream of Thought'],
    examples: [
      'Banner indicating “Draft generated by AI, please review before sending.”',
      'Label chat responses produced by the assistant vs. the human agent.',
    ],
  },
  footprints: {
    title: 'Footprints',
    description:
      'Let users trace the AI’s steps from prompt to result, providing transparency into sources, model versions, and actions taken.',
    designConsiderations: [
      'Log prompts, model selections, connectors, and post-processing steps.',
      'Offer export or sharing for compliance and audit teams.',
      'Highlight deviations or manual overrides during execution.',
    ],
    relatedPatterns: ['Citations', 'Stream of Thought', 'References'],
    examples: [
      'Show which knowledge bases were consulted and when.',
      'Provide a timeline of model calls and intermediate outputs.',
    ],
  },
  'incognito-mode': {
    title: 'Incognito mode',
    description:
      'Let users interact with the AI without storing that session’s data, emphasizing privacy and confidentiality.',
    designConsiderations: [
      'Make the toggle state obvious and persistent across the experience.',
      'Explain what data is still logged (e.g., error reports) if any.',
      'Offer options to export the session before it is deleted.',
    ],
    relatedPatterns: ['Data Ownership', 'Controls', 'Memory'],
    examples: [
      'Temporary brainstorming mode that forgets everything after closing.',
      'Sensitive conversation mode for HR or legal topics.',
    ],
  },
  watermark: {
    title: 'Watermark',
    description:
      'Embed detectable markers on AI-generated content so humans or automated systems can recognize its origin.',
    designConsiderations: [
      'Ensure the watermark does not degrade usability or readability.',
      'Provide metadata or machine-readable tags for programmatic detection.',
      'Clarify whether the watermark persists through edits or conversions.',
    ],
    relatedPatterns: ['Disclosure', 'Caveat', 'Citations'],
    examples: [
      'Overlay a subtle “AI generated” badge on exported images.',
      'Insert metadata tags in PDF exports to flag AI authorship.',
    ],
  },
  'citation-marks': {
    title: 'Citation marks',
    description:
      'Inline numbered badges linking to references or evidence supporting the AI’s statements.',
    designConsiderations: [
      'Keep the badges unobtrusive but clearly interactive.',
      'Allow users to open references in a new tab or copy them easily.',
      'Provide fallback messaging when no citations are available.',
    ],
    relatedPatterns: ['Citations', 'Footprints', 'References'],
    examples: [
      'Numbered superscripts that open a popover with source snippets.',
      'Citation bubbles next to claims in a generated report.',
    ],
  },
}
