name: Notify Discord

on:
  pull_request:
    types: [opened, closed, reopened]
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord (PR)
        if: github.event_name == 'pull_request'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ${{ github.actor }} created pull request #${{ github.event.pull_request.number }} ("${{ github.event.pull_request.title }}") in ${{ github.repository }}
            Description: ${{ github.event.pull_request.body }}
            Source: ${{ github.event.pull_request.head.ref }}
            Target: ${{ github.event.pull_request.base.ref }}
            Status: ${{ github.event.pull_request.state }}
            Merged: ${{ github.event.pull_request.merged }}
      - name: Send to Discord (Push)
        if: github.event_name == 'push'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ${{ github.actor }} pushed to ${{ github.repository }}
            Commit: ${{ github.event.head_commit.message }}
