name: Notify Discord

on:
  pull_request:
    types: [opened, closed, reopened]
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            {% if github.event_name == 'pull_request' %}
            {{ github.event.pull_request.user.login }} created pull request #{{ github.event.pull_request.number }} ({{ github.event.pull_request.title }}) in {{ github.repository }}
            Source
            {{ github.event.pull_request.head.ref }}
            Target
            {{ github.event.pull_request.base.ref }}
            Status
            {{ github.event.pull_request.state }}
            Merge status
            {% if github.event.pull_request.merged %}succeeded{% else %}not merged{% endif %}
            Description
            {{ github.event.pull_request.body }}
            # Checklist
            {% for label in github.event.pull_request.labels %}
            [x] {{ label.name }}
            {% endfor %}
            Reviewers
            {% for reviewer in github.event.pull_request.requested_reviewers %}
            {{ reviewer.login }}
            {% endfor %}
            args: |
              Event: ${{ github.event_name }}
              Repo: ${{ github.repository }}
              Actor: ${{ github.actor }}
              PR #: ${{ github.event.pull_request.number }}
              PR Title: ${{ github.event.pull_request.title }}
              PR Description: ${{ github.event.pull_request.body }}
              Source: ${{ github.event.pull_request.head.ref }}
              Target: ${{ github.event.pull_request.base.ref }}
              Status: ${{ github.event.pull_request.state }}
              Merged: ${{ github.event.pull_request.merged }}
