name: Notify Discord

on:
  pull_request:
    types: [opened, closed, reopened]
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '🔔 Event: ${{ github.event_name }} in ${{ github.repository }} by ${{ github.actor }}'
